// Sample Plant Data (Expand or replace this)
const plants = [
  {
    name: 'Snake Plant',
    scientificName: 'Dracaena trifasciata',
    price: 29.99,
    category: 'Indoor',
    careLevel: 'Easy',
    image: 'https://images.unsplash.com/photo-1593691509543-c55fb32e5cee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80',
    description: 'Excellent air purifier, tolerates low light, requires minimal watering. Very hardy.',
    lightRequirement: 'Low',
    wateringFrequency: 'Rarely',
    inStock: true,
  },
  {
    name: 'Monstera Deliciosa',
    scientificName: 'Monstera deliciosa',
    price: 49.99,
    category: 'Indoor',
    careLevel: 'Moderate',
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80',
    description: 'Iconic split leaves make a bold statement. Prefers bright indirect light and regular watering.',
    lightRequirement: 'Bright Indirect',
    wateringFrequency: 'Weekly',
    inStock: true,
  },
  {
    name: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    price: 79.99,
    category: 'Indoor',
    careLevel: 'Expert',
    image: 'https://images.unsplash.com/photo-1587181804230-1f7f6a137645?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80',
    description: 'A popular but finicky tree with large leaves. Needs bright light and consistent watering. Not for beginners.',
    lightRequirement: 'Bright Indirect',
    wateringFrequency: 'Weekly',
    inStock: false,
  },
  {
    name: 'Lavender',
    scientificName: 'Lavandula angustifolia',
    price: 19.99,
    category: 'Outdoor',
    careLevel: 'Easy',
    image: 'https://images.unsplash.com/photo-1567689369318-8b4b0f55d88d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80',
    description: 'Fragrant purple flowers, loves full sun and well-drained soil. Great for gardens and patios.',
    lightRequirement: 'Direct Sunlight',
    wateringFrequency: 'Weekly',
    inStock: true,
  },
  {
    name: 'ZZ Plant',
    scientificName: 'Zamioculcas zamiifolia',
    price: 32.50,
    category: 'Indoor',
    careLevel: 'Easy',
    image: 'https://images.unsplash.com/photo-1614510891323-0594a1d8a08a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80',
    description: 'Very drought-tolerant and thrives on neglect. Stylish dark green leaves, good for low light office.',
    lightRequirement: 'Low',
    wateringFrequency: 'Rarely',
    inStock: true,
  },
  {
    name: 'Spider Plant',
    scientificName: 'Chlorophytum comosum',
    price: 15.99,
    category: 'Indoor',
    careLevel: 'Easy',
    image: 'https://plus.unsplash.com/premium_photo-1670611171675-7f7a03d116e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80',
    description: 'Produces baby spiderettes, easy to propagate. Adaptable to various light conditions, helps clean air.',
    lightRequirement: 'Medium',
    wateringFrequency: 'Weekly',
    inStock: true,
  }
];

module.exports = plants; 